name: "Jekyll Untrue Minimal"
description: "Welcome to the demo site for 'Jekyll Untrue Minimal'. The description of the blog/site as found in the config YAML doubles as the header rather than a large title or banner. It is here to provide a description of the blog/site as the first text drawn on screen and allows more space for, and less distraction from, pages and posts."

timezone: Europe/London
future: true

url: ''
baseurl: '/jekyll-untrue-minimal'

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: _sass

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
