name: "Jekyll Untrue Minimal"
description: "The description of the blog is up top right here, it's there to give a description of the blog as opposed to a big title, probably a bit longer than this but it should do the trick."

url: ''
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: _sass
